# Generated by Django 3.2.6 on 2021-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharingMyLinkApp', '0006_alter_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
