# Generated by Django 3.2.6 on 2021-09-27 13:21

import SharingMyLinkApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharingMyLinkApp', '0007_alter_room_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomFolder', models.FileField(upload_to=SharingMyLinkApp.models.get_file_path)),
                ('URL_download', models.TextField(default='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharingMyLinkApp.room')),
            ],
        ),
    ]
