# Generated by Django 3.2.6 on 2021-09-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharingMyLinkApp', '0008_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='roomFolder',
            new_name='roomFile',
        ),
        migrations.RemoveField(
            model_name='file',
            name='URL_download',
        ),
    ]
